# Generated by Django 3.0.7 on 2020-07-08 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('idBebida', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamanho', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Borda',
            fields=[
                ('idBorda', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_Borda', models.CharField(max_length=45, verbose_name='Tipo da Borda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idEndereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=2)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=25)),
                ('total_pedido', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('idPizza', models.AutoField(primary_key=True, serialize=False)),
                ('recheio', models.CharField(blank=True, max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamanho', models.CharField(max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('foto', models.FileField(upload_to='media/')),
                ('idBorda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.Borda')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=24)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=45)),
                ('telefone', models.CharField(max_length=11)),
                ('isFunc', models.BooleanField()),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_Pedido',
            fields=[
                ('idProduto_Pedido', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_Pizza', models.IntegerField()),
                ('quantidade_Bebida', models.IntegerField()),
                ('idBebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Bebida')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pedido')),
                ('idPizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Usuario'),
        ),
    ]
