# Generated by Django 3.0.7 on 2020-07-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200708_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('idPizza', models.AutoField(primary_key=True, serialize=False)),
                ('recheio', models.CharField(blank=True, max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamanho', models.CharField(max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('foto', models.FileField(upload_to='media/')),
                ('idBorda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.Borda')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto_Pedido',
        ),
    ]
