# Generated by Django 3.0.7 on 2020-07-08 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20200708_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_Pedido',
            fields=[
                ('idProduto_Pedido', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_Pizza', models.IntegerField()),
                ('quantidade_Bebida', models.IntegerField()),
                ('idBebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Bebida')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pedido')),
                ('idPizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza')),
            ],
        ),
    ]
