# Generated by Django 3.0.7 on 2020-07-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_produto_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media')),
            ],
        ),
    ]
