# Generated by Django 3.0.7 on 2020-07-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_imagens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagens',
        ),
    ]
