# Generated by Django 3.0.7 on 2020-07-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_delete_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidosF',
            fields=[
                ('id_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('id_PedUse', models.IntegerField(default=1)),
                ('Nome_cliente', models.CharField(max_length=50)),
                ('Nome_Pizza', models.CharField(max_length=50)),
                ('Borda', models.CharField(max_length=20)),
                ('Bebida', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=40)),
                ('nBebidas', models.IntegerField(default=0)),
                ('nPizza', models.IntegerField(default=1)),
                ('entrega', models.CharField(max_length=40)),
                ('preco', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='isFunc',
            field=models.BooleanField(default=True),
        ),
    ]
